# Generated by Django 4.0.4 on 2022-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBanco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='subproducto',
            field=models.CharField(max_length=40),
        ),
    ]
